"use client";

import { useState } from "react";
import { ArrowLeft, CalendarPlus, CreditCard, X } from "lucide-react";
import { AdminDateScheduleEditor } from "@/features/admin/AdminDateScheduleEditor";
import { getSuggestedCalendarEndTime } from "@/features/admin/schedules/calendar-grid";
import { AdminManualAppointmentIntakeForm } from "@/features/admin/AdminManualAppointmentIntakeForm";
import type { AdminAppointmentCalendarSlot, AdminDoctorAvailabilityDateOverride, AdminDoctorOption, AdminManualAppointmentPatient } from "@/features/admin/schedules/types";

type DrawerMode = "choose" | "working-hours" | "manual";

export function AdminCalendarSlotDrawer({ dateValue, patients, slot, doctors, overrides, onClose }: { dateValue: string; patients: AdminManualAppointmentPatient[]; slot: AdminAppointmentCalendarSlot; doctors: AdminDoctorOption[]; overrides: AdminDoctorAvailabilityDateOverride[]; onClose: () => void }) {
  const [mode, setMode] = useState<DrawerMode>("choose");
  const canCreateManual = slot.status === "available";
  const manualExplanation = slot.status === "pending_payment" ? "ช่วงเวลานี้ถูกล็อกระหว่างรอชำระเงิน จึงสร้างคำขอใหม่ไม่ได้" : slot.status === "closed" ? "ช่วงเวลานี้ปิดรับนัด จึงสร้างคำขอ Manual ไม่ได้" : "ช่วงเวลานี้ไม่ว่าง จึงสร้างคำขอใหม่ไม่ได้";
  const selectedDoctor = doctors.filter((doctor) => doctor.id === slot.doctorId);
  const suggestedEndTime = getSuggestedCalendarEndTime(slot.timeLabel);

  return <div role="dialog" aria-modal="true" aria-label="จัดการช่วงเวลา" className="fixed inset-0 z-50 flex items-end bg-black/35 sm:items-center sm:justify-center"><section className="max-h-[90vh] w-full overflow-y-auto rounded-t-[16px] bg-white p-5 shadow-xl sm:max-w-lg sm:rounded-[16px]"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-text">จัดการช่วง {slot.timeLabel}</p><p className="mt-1 text-xs text-muted">แพทย์: {slot.doctorName} · วันที่: {dateValue}</p></div><button type="button" onClick={onClose} aria-label="ปิด" className="rounded-[8px] p-2 text-muted"><X className="size-5" /></button></div>{mode === "choose" ? <div className="mt-5 grid gap-3"><p className="text-xs font-bold text-text">เลือกประเภทงาน</p><button type="button" onClick={() => setMode("working-hours")} className="rounded-[8px] border border-border p-4 text-left transition hover:border-primary/40 hover:bg-primary/5"><span className="flex items-center gap-2 text-sm font-bold text-primary"><CalendarPlus className="size-4" />เพิ่มเวลาทำงานแพทย์</span><span className="mt-1 block text-xs leading-5 text-muted">เพิ่มเวลาพิเศษหรือปิดรับนัด โดยใช้การป้องกันฝั่งเซิร์ฟเวอร์เดิม</span></button><button type="button" disabled={!canCreateManual} onClick={() => setMode("manual")} className="rounded-[8px] border border-border p-4 text-left transition enabled:hover:border-primary/40 enabled:hover:bg-primary/5 disabled:cursor-not-allowed disabled:bg-surface"><span className="flex items-center gap-2 text-sm font-bold text-primary"><CreditCard className="size-4" />เพิ่มนัดหมาย Manual</span><span className="mt-1 block text-xs leading-5 text-muted">{canCreateManual ? "สร้างเพียงคำขอรอตรวจยอด ไม่ยืนยันนัดหรือการชำระเงิน" : manualExplanation}</span></button></div> : <div className="mt-4"><button type="button" onClick={() => setMode("choose")} className="inline-flex min-h-9 items-center gap-1 rounded-[8px] border border-border px-3 text-xs font-bold text-primary"><ArrowLeft className="size-3.5" />เปลี่ยนประเภทงาน</button>{mode === "working-hours" ? <div className="mt-3"><AdminDateScheduleEditor doctors={selectedDoctor} overrides={overrides} selectedDate={dateValue} selectedDoctorId={slot.doctorId} selectedStartTime={slot.timeLabel} selectedEndTime={suggestedEndTime} /></div> : <div className="mt-3 rounded-[8px] border border-border p-3"><span className="flex items-center gap-2 text-sm font-bold text-primary"><CreditCard className="size-4" />เพิ่มนัดหมาย Manual</span><AdminManualAppointmentIntakeForm patients={patients} slot={slot} /></div>}</div>}</section></div>;
}
